import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

// CategoryNames : Tshirt, Hoodies, LightStick, Album, POCA, IdolFashion

export const products = [
  {
    _id: uuid(),
    title: "BTS Euphoria",
    group: "BTS",
    price: 199,
    featured: true,
    newArrival: true,
    categoryName: "Tshirt",
    rating: 3,
    img: "https://media.karousell.com/media/photos/products/2021/7/29/bts_tshirt_for_kids_and_adults_1627544395_1902498f_progressive.jpg",
  },
  {
    _id: uuid(),
    title: "BlackPink In Your Area",
    group: "BlackPink",
    price: 299,
    featured: true,
    newArrival: false,
    categoryName: "Tshirt",
    rating: 5,
    img: "https://img.joomcdn.net/643fe1ff724f96cbeea55fe19f323c4201fffba5_original.jpeg",
  },
  {
    _id: uuid(),
    title: "With You Hoodie",
    group: "BTS",
    price: 499,
    oldPrice: "Rs. 699",
    featured: true,
    newArrival: false,
    categoryName: "Hoodies",
    rating: 5,
    img: "https://media.karousell.com/media/photos/products/2022/1/18/wtb_bts_jimin_hoodie_1642473102_113acfee_progressive_thumbnail.jpg",
  },
  {
    _id: uuid(),
    title: "BTS Love Yourself JK Hoodie",
    group: "BTS",
    price: 399,
    oldPrice: "Rs. 599",
    featured: true,
    newArrival: false,
    categoryName: "Hoodies",
    rating: 5,
    img: "  https://cdn.shopify.com/s/files/1/0564/4320/7839/products/product-image-1127129174_2048x2048.jpg?v=1624199417",
  },

  {
    _id: uuid(),
    title: "J-hope Obey T-shirt ",
    group: "BTS",
    price: 1999,
    oldPrice: "5000",
    featured: true,
    newArrival: true,
    categoryName: "IdolFashion",
    rating: 4,
    img: "https://cf.shopee.com.my/file/1e4aab2e5f5aca0a6cc82596f07ae22c",
  },
  {
    _id: uuid(),
    title: "TXT: The Dream Chapter",
    group: "TXT",
    price: 2999,
    oldPrice: "3999",
    featured: true,
    newArrival: true,
    rating: 4,
    categoryName: "Album",
    img: "https://m.media-amazon.com/images/I/81CgJUcPHYL._SL1500_.jpg",
  },
  {
    _id: uuid(),
    title: "Kdrama Quote T-shirt",
    group: "",
    price: 199,
    featured: false,
    newArrival: false,

    categoryName: "Tshirt",
    rating: 4,
    img: "https://m.media-amazon.com/images/I/A13usaonutL._CLa%7C2140%2C2000%7C71VsmhvQqVL.png%7C0%2C0%2C2140%2C2000%2B0.0%2C0.0%2C2140.0%2C2000.0_AC_UL1500_.png",
  },

  {
    _id: uuid(),
    title: "TXT T-shirt",
    group: "TXT",
    price: 499,
    featured: false,
    newArrival: false,
    categoryName: "Tshirt",
    rating: 2,
    img: "https://kpopkstyle.com/wp-content/uploads/2019/11/Multiple-K-pop-Blackpink-Ateez-T-Shirt-Women-TXT-Twice-Tshirt-Kpop-Exo-Boy-with-Luv-Tees-T-shirt-Female-Nct127-gallery-04.jpg",
  },
  {
    _id: uuid(),
    title: "EXO's Chanyeol 170917 Outfit",
    group: "EXO",
    price: 1499,
    featured: true,
    newArrival: true,
    categoryName: "IdolFashion",
    rating: 3,
    img: "https://pm1.narvii.com/6589/df4dc2c67d7140a1a3b2d7b99df010a56aa50602_hq.jpg",
  },
  {
    _id: uuid(),
    title: "BlackPink Lisa's 181118 Hoodie",
    group: "BlackPink",
    price: 999,
    featured: true,
    newArrival: true,
    categoryName: "IdolFashion",
    rating: 3,
    img:"https://i.pinimg.com/736x/bf/f3/f3/bff3f3e51b07d28d2b973dd55984839c.jpg",
  },
  {
    _id: uuid(),
    title: "Twice's Two Page",
    group: "Twice",
    price: 1299,
    oldPrice: "2999",
    featured: false,
    newArrival: false,
    categoryName: "Album",
    rating: 4,
    img: "https://www.kpopusaonline.com/wp-content/uploads/2020/01/591.1.png",
  },

  {
    _id: uuid(),
    title: "Twice's POCA",
    group: "Twice",
    price: 299,
    featured: false,
    newArrival: false,
    categoryName: "POCA",
    rating: 4,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2YTRj0QFYa6I6oyBE9nudWFVzY3jvWYcpMtnOuZATRZcrNrXn0ZoxijdhTfLTR_Ec9nA&usqp=CAU",
  },
  {
    _id: uuid(),
    title: "TXT's POCA",
    group: "TXT",
    price: 199,
    featured: false,
    newArrival: false,
    categoryName: "POCA",
    rating: 2,
    img: "https://m.media-amazon.com/images/I/71j5ktQ9ZhL.jpg",
  },
  {
    _id: uuid(),
    title: "BTS Butter",
    group: "BTS",
    price: 4999,
    featured: false,
    newArrival: true,
    categoryName: "Album",
    rating: 5,
    img: "https://cdn11.bigcommerce.com/s-7uw7zc08qw/images/stencil/1280x1280/products/3840/11406/P000446379__36988.1639705727.jpg?c=2?imbypass=on",
  },

  {
    _id: uuid(),
    title: "BTS ArmyBomb",
    group: "BTS",
    price: 3199,
    featured: false,
    newArrival: false,
    categoryName: "LightSticks",
    rating: 4,
    img: "https://i5.walmartimages.com/asr/fa5f08bc-0151-47b3-88b5-1fa50b091a60_1.b56eab2cb24f057fd4866b949c080e99.jpeg",
  },

  {
    _id: uuid(),
    title: "BlackPink Bl-ping-bong",
    group: "BlackPink",
    price: 1199,
    featured: false,
    newArrival: true,
    categoryName: "LightSticks",
    rating: 4,
    img: "https://img.joomcdn.net/55d741b61c631a513ed2ff3d9cc3f88e488af8f1_original.jpeg",
  },
  {
    _id: uuid(),
    title: "EXO Pharynx",
    group: "EXO",
    price: 2199,
    featured: false,
    newArrival: false,
    categoryName: "LightSticks",
    rating: 3,
    img: "https://canary.contestimg.wish.com/api/webimage/58b7d33df59b8a169b97954c-large.jpg?cache_buster=198b4df22f38b11ec66f13fc8c63c8b0",
  },
];
